# Generated by Django 5.0.6 on 2024-06-28 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_voter_register_date_registed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voter_register',
            new_name='VoterRegistrationModel',
        ),
    ]
