# Generated by Django 5.0.6 on 2024-06-28 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_rename_voter_register_voterregistrationmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterregistrationmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='ElectorialCommisssionOfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eletion_name', models.CharField(max_length=200, unique=True)),
                ('date_deployed', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField()),
                ('eletion_name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommisssionofficermodel')),
            ],
        ),
        migrations.AddField(
            model_name='voterregistrationmodel',
            name='eletion_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommisssionofficermodel'),
        ),
    ]
