# Generated by Django 5.0.6 on 2024-06-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_voterregistrationmodel_registerer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterregistrationmodel',
            name='registerer',
        ),
        migrations.CreateModel(
            name='ElectorialCommissionOfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eletion_name', models.CharField(max_length=200, unique=True)),
                ('date_deployed', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='electiondaymodel',
            name='eletion_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommissionofficermodel'),
        ),
        migrations.AlterField(
            model_name='voterregistrationmodel',
            name='eletion_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommissionofficermodel'),
        ),
        migrations.DeleteModel(
            name='ElectorialCommisssionOfficerModel',
        ),
    ]
