# Generated by Django 5.0.6 on 2024-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_remove_voterregistrationmodel_registerer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electorialcommissionofficermodel',
            name='eletion_name',
            field=models.CharField(max_length=200),
        ),
    ]
