# Generated by Django 5.0.6 on 2024-06-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_electorialcommissionofficermodel_eletion_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electorialcommissionofficermodel',
            old_name='eletion_name',
            new_name='election_name',
        ),
    ]
