# Generated by Django 5.0.6 on 2024-06-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_rename_eletion_name_electorialcommissionofficermodel_election_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electiondaymodel',
            old_name='eletion_name',
            new_name='election_name',
        ),
        migrations.RenameField(
            model_name='voterregistrationmodel',
            old_name='eletion_name',
            new_name='election_name',
        ),
    ]
