# Generated by Django 5.0.1 on 2024-07-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_rename_eletion_name_electiondaymodel_election_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectionDayModel',
        ),
    ]
