# Generated by Django 5.0.6 on 2024-07-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='PortfolioModel',
        ),
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.voterregistrationmodel')),
                ('election_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommissionofficermodel')),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.portfoliomodel')),
            ],
        ),
    ]
