# Generated by Django 5.0.6 on 2024-07-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_rename_portfolio_portfoliomodel_candidatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.candidatemodel')),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.portfoliomodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.voterregistrationmodel')),
            ],
        ),
    ]
