# Generated by Django 5.0.6 on 2024-07-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_votermodel_time_voted_accesselectionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesselectionmodel',
            name='email',
            field=models.EmailField(default='aa@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='accesselectionmodel',
            name='voter_id',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.CreateModel(
            name='VotesnumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_vote', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.candidatemodel')),
            ],
        ),
    ]
