# Generated by Django 5.0.6 on 2024-07-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_alter_accesselectionmodel_election_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessElectionModel',
        ),
    ]
