# Generated by Django 5.0.6 on 2024-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_delete_accesselectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEctionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('voter_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
