# Generated by Django 5.0.6 on 2024-07-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_accessectionmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessEctionModel',
            new_name='AccessElectionModel',
        ),
    ]
