# Generated by Django 5.0.6 on 2024-07-31 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_rename_accessectionmodel_accesselectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemodel',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatemodel',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
