# Generated by Django 5.0.6 on 2024-08-01 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_candidatemodel_date_registered_candidatemodel_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votermodel',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='portfolio_name',
        ),
        migrations.AddField(
            model_name='votermodel',
            name='current_portfolio_index',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votermodel',
            name='election_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base_app.electorialcommissionofficermodel'),
            preserve_default=False,
        ),
    ]
