# Generated by Django 5.0.6 on 2024-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_remove_votermodel_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregistrationmodel',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
